version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - app-network
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
